from eventregistry import *

er = EventRegistry("http://eventregistry.org", verboseOutput = False)

# print er.getNewsSourceUri("The Intercept")
# print er.getNewsSourceUri("CNN")
# print er.getNewsSourceUri("New York Times")
# print er.getNewsSourceUri("The Guardian")
# print er.getNewsSourceUri("Fox News")
# print er.getNewsSourceUri("Forbes")
# print er.getNewsSourceUri("BBC")
# print er.getNewsSourceUri("USA Today")
# print er.getNewsSourceUri("Bloomberg")
# print er.getNewsSourceUri("Reuters")
# print er.getNewsSourceUri("CBS News")
# print er.getNewsSourceUri("ABC News")
# print er.getNewsSourceUri("NBC News")
# print er.getNewsSourceUri("RT English")
# print er.getNewsSourceUri("www.aljazeera.com")
# print er.getNewsSourceUri("National Review Online")
# print er.getNewsSourceUri("Slate")
# print er.getNewsSourceUri("Salon")
# print er.getNewsSourceUri("Mother Jones")
# print er.getNewsSourceUri("The Economist")
# print er.getNewsSourceUri("The Blaze")
# print er.getNewsSourceUri("Daily Caller")
# print er.getNewsSourceUri("Washington Times")
# print er.getNewsSourceUri("Washington Examiner")
# print er.getNewsSourceUri("The Wall Street Journal")
